### ISSUE TITLE
Suggestion: Make POSSIBLE_SOURCE_PATHS configurable

### ISSUE THREAD

**Issue by chaos0815** [TomasVotruba/phpstan-bodyscan#11]
Would like to see the POSSIBLE_SOURCE_PATHS configurable. Currently phpstan-bodyscan does not work for our project out of the box.

**Comment by TomasVotruba** [comment]
Hi, makes sense.
The paths should be picked up from `phpstan.neon` then. Could you send PR to add it?

**Comment by tomasnorre** [comment]
I don't know if I can create a PR for this. But one consideration to take into account is perhaps the `excludePaths` this is an example from my TYPO3 Crawler repository. 

```neon
parameters:
    level: 8
    paths:
        - "Classes/"
        - "Configuration/"
    excludePaths:
        - Tests/Acceptance
        - Classes/Worker/CrawlerWorker.php
        - Classes/CrawlStrategy/GuzzleExecutionStrategy.php
```

**Comment by TomasVotruba** [comment]
@tomasnorre Makes sense to include the exclude paths as well :+1:

**Comment by tomasnorre** [comment]
Just to understand you correct, to include them in the scan or include the excludePaths config to not scan them?

**Comment by TomasVotruba** [comment]
> include the excludePaths config to not scan them

👍

**Comment by TomasVotruba** [comment]
In the meantime, I came across this bug in a project I needed to measure :) 

Resolved in https://github.com/TomasVotruba/phpstan-bodyscan/pull/16
