### ISSUE TITLE
Integrated into Bettergist Collector

### ISSUE THREAD

**Issue by hopeseekr** [TomasVotruba/phpstan-bodyscan#12]
I've implemented this into the Bettergist Collector project.

2024 Q2 doesn't end for another 52 days, but I've already tested it on the Top 100 projects from the results of 2024 Q1, and it behaves awesomely!!

By July 7th, I will have analyzed the top 25,000 PHP projects with this phpstan-bodyscan project, and maybe more. Long-term, it takes about 1 month to run PHPStan against all 345,000+ packagist packages.

Just wanted to let you know.

If you keep this thread open, I will update it with lists of PHP packages for which this library is not compatible, if any.  Phpstan itself fails to run altogether on about 1% of all projects, I won't count those.

This is how I found a lot of edge cases in phpstan over the years. It helps because I might be the only person on this planet (or any other) that frequently runs static analysis, phpunit and more against many thousands of PHP packages on a routine basis.

**Comment by TomasVotruba** [comment]
Hey, thanks for heads up :+1: 
If the PHPStan runs there, so this package as it only uses PHPStan process to analyse code .

What do you plan to do with the results? Some visualisations? :)

**Comment by hopeseekr** [comment]
For sorting PHP packages by "fitness" with your package's output as new fitness parameters.

See my other project: https://github.com/PHPExpertsInc/php-evolver
