### ISSUE TITLE
"PHPStan found in the project" even if no phpstan is installed

### ISSUE THREAD

**Issue by kyriakos** [TomasVotruba/phpstan-bodyscan#13]
Casually added it to a project and came up with

`! [NOTE] PHPStan found in the project, lets run it!
`
I actually don't have PHPStan installed leading into

```
Running: 'bin/phpstan' 'analyse' 'app' 'tests' '--error-format' 'json' '--level' '0' '--configuration' 'phpstan-bodyscan.neon'
PHP Fatal error:  Uncaught TypeError: TomasVotruba\PHPStanBodyscan\Utils\JsonLoader::loadToArray(): Return value must be of type array, null returned in /code/vendor/tomasvotruba/phpstan-bodyscan/src/Utils/JsonLoader.php:16
```

EDIT: looking at the code it seems like this shouldn't have happened. I'll investigate further and post an update.

**Comment by TomasVotruba** [comment]
Thanks for reporting.

I'll make the PHPStan error output is included in the exception.

**Comment by TomasVotruba** [comment]
Try the latest release, it already has the debug output dump.
Feel free to re-open with the debug output.
