### ISSUE TITLE
phpstan-bodyscan doesn't handle different vendor folder

### ISSUE THREAD

**Issue by Hackwar** [TomasVotruba/phpstan-bodyscan#14]
Thanks for this project. I just tried to run this on the Joomla project and phpstan-bodyscan doesn't recognise that the vendor folder is in the /libraries subfolder. phpstan-bodyscan would have to read the `vendor-dir` value from the composer.json and adapt the paths accordingly.

**Comment by TomasVotruba** [comment]
Hi, thanks for suggestion. Makes sense :+1: 

Can you send a PR to add this feature?

**Comment by tomasnorre** [comment]
I might be able to give this a spin. 

Do you prefer to have it an option, that defaults `bin/`? Or should it read the value from `composer.json`?

**Comment by TomasVotruba** [comment]
Ideally read from `composer.json` 🙏

**Comment by tomasnorre** [comment]
This can be closed now ;)

**Comment by TomasVotruba** [comment]
Thank you Tomas :clap: 


Resolved in https://github.com/TomasVotruba/phpstan-bodyscan/pull/15

**Comment by Hackwar** [comment]
Thank you!
