### ISSUE TITLE
Take phpstan.neon.dist into consideration

### ISSUE THREAD

**Issue by phh** [TomasVotruba/phpstan-bodyscan#20]
Right now it looks like it's only taking `phpstan.neon` into consideration when [reusing the configuration](https://github.com/TomasVotruba/phpstan-bodyscan?tab=readme-ov-file#how-does-it-work). It is possible if it could look at `phpstan.neon` first, and then `phpstan.neon.dist` if it does not exist? Perhaps also considering the `phpstan.dist.neon` as well.

https://phpstan.org/config-reference#config-file

> If you do not provide a config file explicitly, PHPStan will look for files named phpstan.neon, phpstan.neon.dist, or phpstan.dist.neon in the current directory.

...

> The usual practice is to have phpstan.neon.dist or phpstan.dist.neon under version control, and allow the user to override certain settings in their environment (on their own computer or on a continuous integration server) by creating phpstan.neon that’s present in .gitignore file. See [Multiple files](https://phpstan.org/config-reference#multiple-files) for more details:

**Comment by TomasVotruba** [comment]
Sounds legit :+1:  Would you like to contribute this?

**Comment by phh** [comment]
Would give it a try :)

**Comment by TomasVotruba** [comment]
Found bit time to fix this in the meantime :) 
https://github.com/TomasVotruba/phpstan-bodyscan/pull/24
