### ISSUE TITLE
Add support for PHPStan config PHP format

### ISSUE THREAD

**Issue by yguedidi** [TomasVotruba/phpstan-bodyscan#22]
In an project I migrated to use PHP format for the PHPStan config, would be great to have it supported by phpstan-bodyscan :)

**Comment by TomasVotruba** [comment]
I see :) 

I think I won't have time to handle this. Do you want to contribute?

**Comment by yguedidi** [comment]
I may give it a try of course when I'll have some free time :)

**Comment by TomasVotruba** [comment]
Sure, feel free to kick of PR when you're ready :+1: 

Closing as accepted
