### ISSUE TITLE
Some feedback after testing

### ISSUE THREAD

**Issue by carlos-granados** [TomasVotruba/phpstan-bodyscan#5]
Tested it and works fine but to get it working I needed to fork it:
- My project uses Symfony 6 and your tool requires version 7 of the console and process components. The tool works perfectly fine with version 6 and will probably work with even lower versions, so you may want to relax those requirements
- You added some "replace" configs to your composer.json. This broke my system as it removed the symfony string component which we use
- Currently you need to have run composer install on your project because it tries to load an autoload file which will not be there if you have not run this

**Comment by TomasVotruba** [comment]
Release will be fully downgraded to require only PHP 7
2+ and solve all of these issues. Stay tuned, expected this week

**Comment by TomasVotruba** [comment]
I managed to make it work :) 

This version is ready to run on PHP 7.2+ with no requirements: https://packagist.org/packages/tomasvotruba/phpstan-bodyscan#0.1.9

Give it a try :+1:

**Comment by carlos-granados** [comment]
Works perfectly with no dependencies and no issues. Great job
