### ISSUE TITLE
Add config parameter to allow you to choose which phpstan config file to use

### ISSUE THREAD

**Issue by carlos-granados** [TomasVotruba/phpstan-bodyscan#6]
If you are already using PHPStan with your project, you may already have a phpstan.neon file with some configurations, exclusions, etc... You may want to re-use this configuration so that you use that as a base line and only get the number of additional errors for additional levels

So we could add a new config parameter that would allow you to point to the neon file to use for the analysis

**Comment by TomasVotruba** [comment]
This is on purpose excluded to give standardized output across various projects.

**Comment by TomasVotruba** [comment]
Reading this issue again, I probably missunderstood your goal.

Bodyscan now picks up existing `phpstan.neon`, and uses paths and excluded paths.
Resolved in https://github.com/TomasVotruba/phpstan-bodyscan/pull/16

**Comment by carlos-granados** [comment]
This came up because I was using your type coverage extension and without reading the values of the existing phpstan configuration I would get a lot of errors in the output because it would not take into account the values for the `type_coverage` parameters.
Now if I run the command without extensions I don't get this error but I get other errors because the Symfony and Doctrine extensions are not enabled. And if I enable the extensions I again get all the errors from the type coverage extension.
I am thinking about other problematic cases, for example if you have set "treatPhpDocTypesAsCertain" to false you may get a list of errors which you have actually ignored in your codebase. Or if you have set some errors to be ignored, they will still be reported by your tool.
So perhaps there could be another flag, something like "use full existing PHPStan configuration" and if you set that to true (would default to false) then your full existing PHPStan configuration *except* the level would be used. What do you think?

**Comment by carlos-granados** [comment]
Also, if you use extensions they may need parameters to work correctly. For example the Symfony extension needs the `containerXmlPath` parameter to work correctly. And your type coverage extension needs the type coverage levels parameters to work fine

**Comment by TomasVotruba** [comment]
Maybe we should take it from another point of view.
What exact data you want to measure?
 How do you want to use those data? To achieve what goal?

**Comment by carlos-granados** [comment]
In my case I wanted to use your tool to get a feeling for how difficult it would be to upgrade to each PHPStan level **with the current PHPStan setup** for our project. If for example, there are not a lot of errors until, say, level 6, then we can spend the effort to update to at least level 5 and then take level 6 with more calm and time. But if I see a lot of errors for levels before 6, which are not actual errors in our current setup, I may find this data less helpful or more difficult to use.

**Comment by TomasVotruba** [comment]
Now I get it, thanks.

Let me think how to redesign this package  to allow use of existing PHPStan setup :+1:

**Comment by TomasVotruba** [comment]
I've refactored the command to use all extension by default now. Give it a try :+1: 

Also I've added `--no-ignore` to do the scan without any ignored errors.
