### ISSUE TITLE
Max level should be 9

### ISSUE THREAD

**Issue by carlos-granados** [TomasVotruba/phpstan-bodyscan#7]
Currently if you don't use the max level config value it defaults to 8. This should be 9 which is the current max level supported by phpstan

**Comment by TomasVotruba** [comment]
This is on purpose, as mixed level is optional extreme, not saint default.

You can extend it by max-level option 👍

**Comment by carlos-granados** [comment]
a) This isn't actually doing the upgrade, just telling you the number of errors for each level, so I think that also knowing that number for level 9 by default would be useful
b) If you don't agree with this, then it would be helpful to mention the reasons in the docs
Thanks!! : -)
