### ISSUE TITLE
Add a "increase" column in the result table

### ISSUE THREAD

**Issue by carlos-granados** [TomasVotruba/phpstan-bodyscan#8]
Add a new "increase" column in the result table which is the difference between the errors in the current level and the errors in the previous level. This makes it easier to see the effort required for each of the levels

**Comment by TomasVotruba** [comment]
Thanks for suggestion. 
I'm not planning this, to keep the output simple to read with single information.

**Comment by TomasVotruba** [comment]
Giving 2nd thought to this, it would be really motivating to see small numbers on 3rd column :)

**Comment by TomasVotruba** [comment]
Done :rocket: 

https://github.com/TomasVotruba/phpstan-bodyscan/pull/25
