### ISSUE TITLE
Count errors by identifier

### ISSUE THREAD

**Issue by staabm** [TomasVotruba/phpstan-bodyscan#9]
In phpstan 1.11 every error will get an error identifier. 

Would be great this tool could count the number of errors per identifier

**Comment by TomasVotruba** [comment]
I'm affraid this would yield thousands of lines report. Not sure how it would be used in practice to make the change happen.

Goal of this package is to keep it simple and inspire to change, so if you can come up with some "top-10 identiefiers", we could give it a go = PR welcomed :+1:
